# Generated by Django 2.2 on 2020-05-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdw_database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='stuEmail',
            field=models.CharField(default='123@qq.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='stuName',
            field=models.CharField(default='terry', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='GPA',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='stuID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
