# Generated by Django 2.2 on 2020-05-11 08:51

from django.db import migrations, models
import django.db.models.deletion
import sdw_database.models


class Migration(migrations.Migration):

    dependencies = [
        ('sdw_database', '0002_auto_20200510_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('courseTitle', models.CharField(max_length=50, null=True)),
                ('numberOfParticipants', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Login',
            fields=[
                ('stuID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sdw_database.Student')),
                ('userName', models.CharField(max_length=10)),
                ('password', models.CharField(default='123456', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Submission_Course',
            fields=[
                ('submissionID', models.IntegerField(primary_key=True, serialize=False)),
                ('submissionTitle', models.CharField(max_length=30, null=True)),
                ('percentage', models.CharField(default='0%', max_length=5)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sdw_database.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('staffID', models.IntegerField(primary_key=True, serialize=False)),
                ('staffName', models.CharField(max_length=30, null=True)),
                ('staffEmail', models.EmailField(max_length=60, null=True)),
                ('programme', models.CharField(max_length=100, null=True)),
                ('userName', models.CharField(max_length=20)),
                ('password', models.CharField(default='123456', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Course',
            fields=[
                ('teamID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('numberOfMembers', models.IntegerField(default=0)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sdw_database.Course')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='stuEmail',
            field=models.EmailField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='stuName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Submission_Contribution_Leader',
            fields=[
                ('submissionID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sdw_database.Submission_Course')),
                ('stuID', models.FloatField(verbose_name=sdw_database.models.Student)),
                ('assessFromMember', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='staffID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sdw_database.Teacher'),
        ),
        migrations.CreateModel(
            name='Team_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuName', models.CharField(max_length=30, null=True)),
                ('leader', models.BooleanField(default=False)),
                ('stuID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sdw_database.Student')),
                ('teamID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sdw_database.Team_Course')),
            ],
            options={
                'unique_together': {('teamID', 'stuID')},
            },
        ),
        migrations.CreateModel(
            name='Submission_Contribution_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessFromLeader', models.FloatField(default=1.0)),
                ('stuID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sdw_database.Student')),
                ('submissionID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sdw_database.Submission_Course')),
            ],
            options={
                'unique_together': {('submissionID', 'stuID')},
            },
        ),
    ]
