# Generated by Django 2.2 on 2020-05-14 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdw_database', '0003_auto_20200511_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLogin',
            fields=[
                ('stuID', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=10)),
                ('password', models.CharField(default='123456', max_length=20)),
            ],
            options={
                'ordering': ['stuID'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionContributionLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessFromMember', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionContributionMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessFromLeader', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissionID', models.IntegerField(unique=True)),
                ('submissionTitle', models.CharField(max_length=30, null=True)),
                ('percentage', models.CharField(default='0%', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamID', models.CharField(max_length=15, unique=True)),
                ('numberOfMembers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuName', models.CharField(max_length=30, null=True)),
                ('leader', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='submission_contribution_leader',
            name='submissionID',
        ),
        migrations.AlterUniqueTogether(
            name='submission_contribution_member',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='submission_contribution_member',
            name='stuID',
        ),
        migrations.RemoveField(
            model_name='submission_contribution_member',
            name='submissionID',
        ),
        migrations.RemoveField(
            model_name='submission_course',
            name='courseID',
        ),
        migrations.RemoveField(
            model_name='team_course',
            name='courseID',
        ),
        migrations.AlterUniqueTogether(
            name='team_member',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='team_member',
            name='stuID',
        ),
        migrations.RemoveField(
            model_name='team_member',
            name='teamID',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['stuID']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['staffID']},
        ),
        migrations.AlterField(
            model_name='course',
            name='staffID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdw_database.Teacher'),
        ),
        migrations.DeleteModel(
            name='Student_Login',
        ),
        migrations.DeleteModel(
            name='Submission_Contribution_Leader',
        ),
        migrations.DeleteModel(
            name='Submission_Contribution_Member',
        ),
        migrations.DeleteModel(
            name='Submission_Course',
        ),
        migrations.DeleteModel(
            name='Team_Course',
        ),
        migrations.DeleteModel(
            name='Team_Member',
        ),
        migrations.AddField(
            model_name='teammembership',
            name='stuID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdw_database.Student'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='teamID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdw_database.Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='courseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdw_database.Course'),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(through='sdw_database.TeamMembership', to='sdw_database.Student'),
        ),
        migrations.AddField(
            model_name='submissioncourse',
            name='courseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdw_database.Course'),
        ),
        migrations.AddField(
            model_name='submissioncontributionmember',
            name='stuID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sdw_database.Student'),
        ),
        migrations.AddField(
            model_name='submissioncontributionmember',
            name='submissionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdw_database.SubmissionCourse'),
        ),
        migrations.AddField(
            model_name='submissioncontributionleader',
            name='stuID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdw_database.Student'),
        ),
        migrations.AddField(
            model_name='submissioncontributionleader',
            name='submissionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdw_database.SubmissionCourse'),
        ),
        migrations.AlterUniqueTogether(
            name='submissioncontributionmember',
            unique_together={('submissionID', 'stuID')},
        ),
        migrations.AlterUniqueTogether(
            name='submissioncontributionleader',
            unique_together={('submissionID', 'stuID')},
        ),
    ]
