# Generated by Django 2.2 on 2020-05-14 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdw_database', '0006_auto_20200514_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('staffID', models.IntegerField(primary_key=True, serialize=False)),
                ('staffName', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('courseTitle', models.CharField(max_length=50, null=True)),
                ('staffID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdw_database.Teacher')),
            ],
        ),
    ]
