# Generated by Django 2.2 on 2020-05-14 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdw_database', '0007_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='staffID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sdw_database.Teacher'),
        ),
    ]
