# Generated by Django 2.2 on 2020-05-14 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdw_database', '0008_auto_20200514_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.RemoveField(
            model_name='course',
            name='courseTitle',
        ),
        migrations.RemoveField(
            model_name='student',
            name='GPA',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stuEmail',
        ),
        migrations.AlterField(
            model_name='course',
            name='staffID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdw_database.Teacher'),
        ),
    ]
