# Generated by Django 2.2 on 2020-05-15 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdw_database', '0011_auto_20200515_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='staffIDs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sdw_database.Teacher'),
        ),
    ]
