# Generated by Django 2.2 on 2020-05-15 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdw_database', '0012_auto_20200515_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLogin',
            fields=[
                ('stuID', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=10)),
                ('password', models.CharField(default='123456', max_length=20)),
            ],
            options={
                'ordering': ['stuID'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamID', models.CharField(max_length=15, unique=True)),
                ('numberOfMembers', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['stuID']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['staffID']},
        ),
        migrations.AddField(
            model_name='course',
            name='courseTitle',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='numberOfParticipants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='GPA',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='stuEmail',
            field=models.EmailField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='123456', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='programme',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='staffEmail',
            field=models.EmailField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='userName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='staffIDs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdw_database.Teacher'),
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuName', models.CharField(max_length=30, null=True)),
                ('leader', models.BooleanField(default=False)),
                ('stuID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdw_database.Student')),
                ('teamID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdw_database.Team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='courseID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdw_database.Course'),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(through='sdw_database.TeamMembership', to='sdw_database.Student'),
        ),
        migrations.CreateModel(
            name='SubmissionCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissionID', models.IntegerField(unique=True)),
                ('submissionTitle', models.CharField(max_length=30, null=True)),
                ('percentage', models.CharField(default='0%', max_length=5)),
                ('courseID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdw_database.Course')),
            ],
        ),
        migrations.CreateModel(
            name='MemberContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessFromLeader', models.FloatField(default=1.0)),
                ('stuID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdw_database.Student')),
                ('submissionID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdw_database.SubmissionCourse')),
            ],
            options={
                'abstract': False,
                'unique_together': {('submissionID', 'stuID')},
            },
        ),
        migrations.CreateModel(
            name='LeaderContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessFromMember', models.IntegerField(default=0)),
                ('stuID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdw_database.Student')),
                ('submissionID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdw_database.SubmissionCourse')),
            ],
            options={
                'abstract': False,
                'unique_together': {('submissionID', 'stuID')},
            },
        ),
    ]
